apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-user: eWNvbXBhbnk=  # Base64 encoded "ycompany"
  postgres-password: cGFzc3dvcmQ=  # Base64 encoded "password"