apiVersion: apps/v1
kind: Deployment
metadata:
  name: claims-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: claims-service
  template:
    metadata:
      labels:
        app: claims-service
    spec:
      containers:
      - name: claims-service
        image: claims-service:latest
        imagePullPolicy: Never

        ports:
        - containerPort: 5001
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:5001"
        - name: ConnectionStrings__DefaultConnection
          value: "Host=postgres;Database=YCompanyClaimsDb;Username=ycompany;Password=password;"
---
apiVersion: v1
kind: Service
metadata:
  name: claims-service
spec:
  selector:
    app: claims-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001