apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: document-service
  template:
    metadata:
      labels:
        app: document-service
    spec:
      containers:
      - name: document-service
        image: document-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5002
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:5000"
        - name: ConnectionStrings__DefaultConnection
          value: "Host=postgres;Database=YCompanyClaimsDb;Username=ycompany;Password=password;"
---
apiVersion: v1
kind: Service
metadata:
  name: document-service
spec:
  selector:
    app: document-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002