apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workshop-service
  template:
    metadata:
      labels:
        app: workshop-service
    spec:
      containers:
      - name: workshop-service
        image: workshop-service:latest
        imagePullPolicy: Never

        ports:
        - containerPort: 5003
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:5003"
        - name: ConnectionStrings__DefaultConnection
          value: "Host=postgres;Database=YCompanyClaimsDb;Username=ycompany;Password=password;"
---
apiVersion: v1
kind: Service
metadata:
  name: workshop-service
spec:
  selector:
    app: workshop-service
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003